In [17]:
# Create a vector as input
age <- c(55,57,56,52,51,59,58,53,59,55,60,60,60,60,52,55,56,51,60,52,54,
         56,52,57,54,56,58,53,53,50,55,51,57,60,57,55,51,50,57,58)

# Convert to factor
factor_age <- factor(age)

levels(factor_age)
length(factor_age)
table(factor_age)

# Divide into 5 ranges (auto)
age_range <- cut(age,
                 breaks = 5,
                 include.lowest = TRUE,
                 right = TRUE)
# Frequency of each range
table(age_range)

[1] "50" "51" "52" "53" "54" "55" "56" "57" "58" "59" "60"

[1] 40

factor_age
50 51 52 53 54 55 56 57 58 59 60 
 2  4  4  3  2  5  4  5  3  2  6 

age_range
[50,52] (52,54] (54,56] (56,58] (58,60] 
     10       5       9       8       8 

In [18]:
# Vector V1
V1 <- c(2,3,1,5,4,6,8,7,9)

# 1. Create 3x3 Matrix-1
Matrix1 <- matrix(V1, nrow = 3, ncol = 3, byrow = TRUE)
Matrix1

# 2. Transpose Matrix-1 - Matrix-2
Matrix2 <- t(Matrix1)
Matrix2

# 3. Rename rows and columns
rownames(Matrix1) <- paste("R", 1:3, sep = "")
colnames(Matrix1) <- paste("C", 1:3, sep = "")

rownames(Matrix2) <- paste("R", 1:3, sep = "")
colnames(Matrix2) <- paste("C", 1:3, sep = "")

Matrix1
Matrix2

# 4. Add
Add <- Matrix1 + Matrix2
Add

# 5. Subtract
Subtract <- Matrix1 - Matrix2
Subtract

# 6. Multiply
Multiply <- Matrix1 * Matrix2
Multiply

# 7. Divide
Divide <- Matrix1 / Matrix2
Divide

2,3,1
5,4,6
8,7,9


2,5,8
3,4,7
1,6,9


,C1,C2,C3
R1,2,3,1
R2,5,4,6
R3,8,7,9


,C1,C2,C3
R1,2,5,8
R2,3,4,7
R3,1,6,9


,C1,C2,C3
R1,4,8,9
R2,8,8,13
R3,9,13,18


,C1,C2,C3
R1,0,-2,-7
R2,2,0,-1
R3,7,1,0


,C1,C2,C3
R1,4,15,8
R2,15,16,42
R3,8,42,81


,C1,C2,C3
R1,1.000000,0.600000,0.1250000
R2,1.666667,1.000000,0.8571429
R3,8.000000,1.166667,1.0000000


In [21]:
# first array
Array1 <- array(1:24, dim = c(2, 4, 3))

# Print Array1
cat("Array1:\n")
for(i in 1:dim(Array1)[3]){
  cat("\nMatrix", i, ":\n")
  print(Array1[ , , i])
}

# second array
Array2 <- array(25:54, dim = c(3, 2, 5))

# rint Array2 nicely
cat("\nArray2:\n")
for(i in 1:dim(Array2)[3]){
  cat("\nMatrix", i, ":\n")
  print(Array2[ , , i])
}

#Print
second_row_Array1 <- Array1[2, , 2]
cat("\nThe second row of the second matrix of the array:\n")
print(second_row_Array1)

# Print
element_Array2 <- Array2[3, 2, 1]
cat("\nThe element in the 3rd row and 2nd column of the 1st matrix:\n")
print(element_Array2)

Array1:

Matrix 1 :
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

Matrix 2 :
     [,1] [,2] [,3] [,4]
[1,]    9   11   13   15
[2,]   10   12   14   16

Matrix 3 :
     [,1] [,2] [,3] [,4]
[1,]   17   19   21   23
[2,]   18   20   22   24

Array2:

Matrix 1 :
     [,1] [,2]
[1,]   25   28
[2,]   26   29
[3,]   27   30

Matrix 2 :
     [,1] [,2]
[1,]   31   34
[2,]   32   35
[3,]   33   36

Matrix 3 :
     [,1] [,2]
[1,]   37   40
[2,]   38   41
[3,]   39   42

Matrix 4 :
     [,1] [,2]
[1,]   43   46
[2,]   44   47
[3,]   45   48

Matrix 5 :
     [,1] [,2]
[1,]   49   52
[2,]   50   53
[3,]   51   54

The second row of the second matrix of the array:
[1] 10 12 14 16

The element in the 3rd row and 2nd column of the 1st matrix:
[1] 30
